### ISSUE TITLE
Safestack option only effective when Makefile includes "USE_HARDENING=  safestack"

### ISSUE THREAD

**Issue by utrenkner** [HardenedBSD/hardenedbsd-ports#68]
While testing www/h2o, I found out that ``make config``* shows the safestack option - but it does not have any effect on the compilation. This is different from the pie and relro options.

When the Makefile contains the line
```
USE_HARDENING=  safestack
```
the safestack choice is honored in both cases, on and off (with on begin the default, obviously).

* actually, I did not use ``make config`` but poudriere's equivalent ``poudriere options -C www/h2o``. In the relative options file of poudriere, the choice is correctly saved. But it does not have any effect as long as safestack is not included already in the Makefile.

**Comment by lattera** [comment]
Assigning to Franco to diagnose.

**Comment by fichtner** [comment]
This was a design decision, which bites back now. There are two options:

1. always annotate all options, even if not applicable. This would cause a lot of spurious "options changed" rebuilds and reinstalls in the future, especially when a new hardening option is added.

2. move the hardening code closer to the option handling in order to make a more educated guess about the situation we're in. We are currently running a sort of pre-parser to options, which does not have all the necessary information without duplicating code that bsd.options.mk already has.

I'm favouring 2. What do you guys think?

**Comment by utrenkner** [comment]
OK, then I would agree with option 2. But there should be a clear warning that the hardening options shown may not actually be available. 

When I asked on the mailing list on how to switch on SafeStack for a specific port, Shawn showed me the ``make config`` way. Thus, when I tested www/h2o and reported back that it worked with SafeStack, I had actually never compiled it with this option.

And because of this, the new-found problem with h2o cost me ca. half a day of work: As I "knew" that I had already successfully compiled and run it with SafeStack, I tried for hours to find the cause of the problem elsewhere (changes in dependencies).

**Comment by lattera** [comment]
I'm okay with option 2. It looks like ```make config``` is pretty much broken with regards to the hardening framework as it stands right now.

**Comment by fichtner** [comment]
As this is a frustrating uphill battle, for HardenedBSD option 1) should be implemented as it previously was. I'll do some safeguard for OPNsense later to flip the behaviour so our trees do not go out of sync. Should be all better with bee2610.
